"""add rule outcome to jev decisions

Revision ID: 6a09c977dbc8
Revises: fb9347216bbb
Create Date: 2026-09-30 07:18:39.981310
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6a09c977dbc8'
down_revision: str | None = 'fb9347216bbb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jev_decisions', sa.Column('permitted_action', sa.String(length=30), nullable=True))
    op.add_column('jev_decisions', sa.Column('requires_approval', sa.Boolean(), nullable=True))
    op.add_column('jev_decisions', sa.Column('rule_hits', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jev_decisions', 'rule_hits')
    op.drop_column('jev_decisions', 'requires_approval')
    op.drop_column('jev_decisions', 'permitted_action')
    # ### end Alembic commands ###
