"""add urgency score to jev decisions

Revision ID: cc7f6cde80b3
Revises: 6a09c977dbc8
Create Date: 2026-09-30 09:44:58.778166
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cc7f6cde80b3'
down_revision: str | None = '6a09c977dbc8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jev_decisions', sa.Column('urgency_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jev_decisions', 'urgency_score')
    # ### end Alembic commands ###
